import 'package:json_annotation/json_annotation.dart';

part 'company_info_model.g.dart'; // This will be generated by json_serializable

@JsonSerializable()
class CompanyInfoModel {
  final Headquarters headquarters;
  final Links links;
  final String name;
  final String founder;
  final int founded;
  final int employees;
  final int vehicles;
  @JsonKey(name: 'launch_sites')
  final int launchSites;
  @JsonKey(name: 'test_sites')
  final int testSites;
  final String ceo;
  final String cto;
  final String coo;
  @JsonKey(name: 'cto_propulsion')
  final String ctoPropulsion;
  final int valuation;
  final String summary;
  final String id;

  CompanyInfoModel({
    required this.headquarters,
    required this.links,
    required this.name,
    required this.founder,
    required this.founded,
    required this.employees,
    required this.vehicles,
    required this.launchSites,
    required this.testSites,
    required this.ceo,
    required this.cto,
    required this.coo,
    required this.ctoPropulsion,
    required this.valuation,
    required this.summary,
    required this.id,
  });

  factory CompanyInfoModel.fromJson(Map<String, dynamic> json) =>
      _$CompanyInfoModelFromJson(json);
  Map<String, dynamic> toJson() => _$CompanyInfoModelToJson(this);
}

@JsonSerializable()
class Headquarters {
  final String address;
  final String city;
  final String state;

  Headquarters({
    required this.address,
    required this.city,
    required this.state,
  });

  factory Headquarters.fromJson(Map<String, dynamic> json) =>
      _$HeadquartersFromJson(json);
  Map<String, dynamic> toJson() => _$HeadquartersToJson(this);
}

@JsonSerializable()
class Links {
  final String website;
  final String flickr;
  final String twitter;
  @JsonKey(name: 'elon_twitter')
  final String elonTwitter;

  Links({
    required this.website,
    required this.flickr,
    required this.twitter,
    required this.elonTwitter,
  });

  factory Links.fromJson(Map<String, dynamic> json) => _$LinksFromJson(json);
  Map<String, dynamic> toJson() => _$LinksToJson(this);
}
